# PerPlayerKit Neon Main Menu Configuration
# High-energy cyber-themed layout for the neon theme

name: "Neon Main Menu"
title: "&f&l⟦ &b&lCYBER KIT TERMINAL &f&l⟧"
size: 54  # 6 rows for maximum cyber aesthetic
theme: "neon"

# Cyber grid layout
layout:
  type: "custom"
  pattern:
    - "xxxxxxxxx"  # Row 0: Electric border
    - "x1234567x"  # Row 1: Kit slots
    - "xabcdefgx"  # Row 2: Enderchest slots
    - "xhhijklmx"  # Row 3: Primary functions
    - "xnopqrstx"  # Row 4: Advanced functions
    - "xxxxxxxxx"  # Row 5: Electric border

  definitions:
    x: "electric_border"
    1-7: "cyber_kit_slots"
    a-g: "cyber_ec_slots"
    h: "public_kits"
    i: "kit_room"
    j: "reload_config"
    k: "regear"
    l: "copy_kit"
    m: "cyber_stats"
    n: "backup_system"
    o: "theme_matrix"
    p: "admin_panel"
    q: "system_monitor"
    r: "data_export"
    s: "help_system"
    t: "power_button"

# Cyber data context with electric variables
data:
  player_name: "{player.name}"
  server_name: "&b⚡ CYBER SERVER ⚡"
  current_theme: "neon"
  system_status: "ONLINE"
  connection_strength: "100%"
  data_integrity: "SECURE"
  
  # Kit data with cyber formatting
  kit_1: "{player.kit.1}"
  kit_2: "{player.kit.2}"
  kit_3: "{player.kit.3}"
  kit_4: "{player.kit.4}"
  kit_5: "{player.kit.5}"
  kit_6: "{player.kit.6}"
  kit_7: "{player.kit.7}"
  
  # Enderchest data with encryption labels
  ec_1: "{player.enderchest.1}"
  ec_2: "{player.enderchest.2}"
  ec_3: "{player.enderchest.3}"
  ec_4: "{player.enderchest.4}"
  ec_5: "{player.enderchest.5}"
  ec_6: "{player.enderchest.6}"
  ec_7: "{player.enderchest.7}"

# Cyber component configurations
components:
  
  # Electrified kit slots
  cyber_kit_slots:
    type: "kit_slot"
    slots: [10, 11, 12, 13, 14, 15, 16]
    data_binding: "player.kits"
    actions:
      left_click:
        type: "load_kit"
        params:
          slot: "{slot_number}"
          animation: "electric_surge"
      right_click:
        type: "save_kit"
        params:
          slot: "{slot_number}"
          confirmation: true
          animation: "data_upload"
      shift_left_click:
        type: "open_kit_preview"
        params:
          slot: "{slot_number}"
          mode: "holographic"
  
  # Encrypted enderchest slots
  cyber_ec_slots:
    type: "enderchest_slot"
    slots: [19, 20, 21, 22, 23, 24, 25]
    data_binding: "player.enderchests"
    actions:
      left_click:
        type: "open_enderchest"
        params:
          slot: "{slot_number}"
          animation: "decrypt_data"
      right_click:
        type: "save_enderchest"
        params:
          slot: "{slot_number}"
          confirmation: true
          animation: "encrypt_data"
  
  # Cyber function buttons
  public_kits:
    type: "button"
    slot: 28
    material: "CYAN_STAINED_GLASS"
    name: "&f&l⟦ &b&lPUBLIC ARCHIVES &f&l⟧"
    lore:
      - "&3» Access shared kit databases"
      - "&3» Download pre-configured loadouts"
      - "&3» Community-verified templates"
      - ""
      - "&e⚡ CLICK TO ACCESS ⚡"
    enchanted: true
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "public-kits-neon"
    conditions:
      - type: "permission"
        value: "perplayerkit.publickit"
  
  kit_room:
    type: "button"
    slot: 29
    material: "LIGHT_BLUE_CONCRETE"
    name: "&f&l⟦ &b&lCONSTRUCTION BAY &f&l⟧"
    lore:
      - "&3» Enter collaborative workspace"
      - "&3» Build kits with team members"
      - "&3» Real-time construction tools"
      - ""
      - "&e⚡ ADMIN ACCESS REQUIRED ⚡"
    enchanted: true
    actions:
      left_click:
        type: "execute_command"
        params:
          command: "kitroom"
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  reload_config:
    type: "button"
    slot: 30
    material: "CYAN_CONCRETE"
    name: "&f&l⟦ &b&lSYSTEM REFRESH &f&l⟧"
    lore:
      - "&3» Reload all system configurations"
      - "&3» Apply updates instantly"
      - "&3» Refresh GUI templates"
      - ""
      - "&d⚡ SYSTEM ADMINISTRATION ⚡"
    enchanted: true
    actions:
      left_click:
        type: "reload_config"
        params:
          confirmation: true
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  regear:
    type: "button"
    slot: 31
    material: "LIME_CONCRETE"
    name: "&f&l⟦ &a&lQUICK DEPLOY &f&l⟧"
    lore:
      - "&3» Instant last-kit deployment"
      - "&3» Emergency respawn protocol"
      - "&3» Auto-equipment system"
      - ""
      - "&e⚡ EXECUTE PROTOCOL ⚡"
    actions:
      left_click:
        type: "execute_command"
        params:
          command: "regear"
    conditions:
      - type: "permission"
        value: "perplayerkit.regear"
  
  copy_kit:
    type: "button"
    slot: 32
    material: "YELLOW_CONCRETE"
    name: "&f&l⟦ &e&lDATA CLONE &f&l⟧"
    lore:
      - "&3» Clone current inventory data"
      - "&3» Duplicate to target slot"
      - "&3» Preserve all metadata"
      - ""
      - "&e⚡ INITIATE CLONING ⚡"
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "kit-copy-neon"
    conditions:
      - type: "permission"
        value: "perplayerkit.copykit"
  
  cyber_stats:
    type: "button"
    slot: 33
    material: "PRISMARINE_CRYSTALS"
    name: "&f&l⟦ &b&lSYSTEM STATS &f&l⟧"
    lore:
      - "&3» View player statistics"
      - "&3» Kit usage analytics"
      - "&3» Performance metrics"
      - ""
      - "&b▰ Connection: {connection_strength}"
      - "&b▰ Status: {system_status}"
      - "&b▰ Security: {data_integrity}"
      - ""
      - "&e⚡ ANALYZE DATA ⚡"
    enchanted: true
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "player-stats"
  
  backup_system:
    type: "button"
    slot: 37
    material: "GLOW_INK_SAC"
    name: "&f&l⟦ &d&lBACKUP MATRIX &f&l⟧"
    lore:
      - "&3» Create data backups"
      - "&3» Restore from archives"
      - "&3» Emergency recovery"
      - ""
      - "&d⚡ ADMIN FUNCTION ⚡"
    enchanted: true
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "backup-system"
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  theme_matrix:
    type: "button"
    slot: 38
    material: "ENDER_EYE"
    name: "&f&l⟦ &d&lTHEME MATRIX &f&l⟧"
    lore:
      - "&3» Access visual themes"
      - "&3» Current: &bNeon Cyber"
      - "&3» Switch interface styles"
      - ""
      - "&7Available matrices:"
      - "&8• &7Default Core"
      - "&8• &5Dark Portal"
      - "&8• &bNeon Cyber &8(active)"
      - "&8• &6Medieval Realm"
      - ""
      - "&e⚡ CHANGE MATRIX ⚡"
    enchanted: true
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "theme-selector-neon"
  
  admin_panel:
    type: "button"
    slot: 39
    material: "REDSTONE_BLOCK"
    name: "&f&l⟦ &c&lADMIN CORE &f&l⟧"
    lore:
      - "&3» Administrative controls"
      - "&3» Server management"
      - "&3» User oversight"
      - ""
      - "&c⚡ HIGH CLEARANCE ⚡"
    enchanted: true
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "admin-panel"
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  system_monitor:
    type: "button"
    slot: 40
    material: "OBSERVER"
    name: "&f&l⟦ &6&lSYSTEM MONITOR &f&l⟧"
    lore:
      - "&3» Real-time system status"
      - "&3» Performance monitoring"
      - "&3» Resource utilization"
      - ""
      - "&6⚡ MONITOR ACTIVE ⚡"
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "system-monitor"
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  data_export:
    type: "button"
    slot: 41
    material: "HOPPER"
    name: "&f&l⟦ &e&lDATA EXPORT &f&l⟧"
    lore:
      - "&3» Export kit configurations"
      - "&3» Generate backup files"
      - "&3» Share data packages"
      - ""
      - "&e⚡ EXPORT PROTOCOL ⚡"
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "data-export"
    conditions:
      - type: "permission"
        value: "perplayerkit.admin"
  
  help_system:
    type: "button"
    slot: 42
    material: "ACACIA_SIGN"
    name: "&f&l⟦ &a&lHELP DATABASE &f&l⟧"
    lore:
      - "&3» System documentation"
      - "&3» Command reference"
      - "&3» Troubleshooting guide"
      - ""
      - "&a⚡ ACCESS HELP ⚡"
    actions:
      left_click:
        type: "open_gui"
        params:
          gui: "help-system"
  
  power_button:
    type: "button"
    slot: 43
    material: "REDSTONE_TORCH"
    name: "&f&l⟦ &c&lPOWER DOWN &f&l⟧"
    lore:
      - "&3» Close terminal interface"
      - "&3» Save session data"
      - "&3» Return to game world"
      - ""
      - "&c⚡ SHUTDOWN SEQUENCE ⚡"
    actions:
      left_click:
        type: "close_gui"
        params:
          save_session: true
  
  # Electric border elements
  electric_border:
    type: "border"
    slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]
    material: "CYAN_STAINED_GLASS_PANE"
    name: "&b⚡"
    enchanted: true
    hide_flags: true

# Neon cyber effects
effects:
  open_sound: "ENTITY_LIGHTNING_BOLT_THUNDER"
  close_sound: "BLOCK_BEACON_DEACTIVATE"
  
  particle_effects:
    enabled: true
    type: "ELECTRIC_SPARK"
    count: 10
    
  animations:
    slot_highlight: "electric_pulse"
    button_hover: "neon_glow"
    data_transfer: "lightning_bolt"

# Advanced cyber features
features:
  auto_refresh: true
  refresh_interval: 15  # seconds - faster for neon theme
  
  hover_previews: true
  holographic_display: true
  
  particle_trails: true
  sound_effects: true
  
  theme_persistence: true
  session_tracking: true
  
  cyber_animations: true
  electric_transitions: true