# PerPlayerKit Theme Selector GUI
# Allows players to switch between different GUI themes

name: "Theme Selector"
title: "&f&lTheme Selection"
size: 27  # 3 rows
theme: "default"  # Uses default theme for neutrality

# Simple centered layout
layout:
  type: "custom"
  pattern:
    - "bbbbbbbbb"  # Row 0: Border
    - "b1234567b"  # Row 1: Theme options with spacers
    - "bbbbbbbbb"  # Row 2: Border

  definitions:
    b: "border"
    1: "default_theme"
    2: "spacer"
    3: "dark_theme"
    4: "spacer"
    5: "neon_theme"
    6: "spacer"
    7: "medieval_theme"

# Theme data
data:
  current_theme: "{player.current_theme}"
  player_name: "{player.name}"

components:
  
  # Default theme option
  default_theme:
    type: "button"
    slot: 10
    material: "BLUE_STAINED_GLASS"
    name: "&9&lDefault Theme"
    lore:
      - "&7Classic blue interface with"
      - "&7traditional Minecraft styling"
      - ""
      - "&7Features:"
      - "&8• Clean and simple design"
      - "&8• Easy to navigate"
      - "&8• Universal compatibility"
      - ""
      - "{if:{equals:{player.current_theme}:default}:&a✓ Currently Active:&e» Click to Activate}"
    enchant_if: "{equals:{player.current_theme}:default}"
    actions:
      left_click:
        type: "switch_theme"
        params:
          theme: "default"
          gui: "main-menu"
  
  # Dark theme option
  dark_theme:
    type: "button"
    slot: 12
    material: "PURPLE_STAINED_GLASS"
    name: "&5&lDark Theme"
    lore:
      - "&7Sleek dark interface with"
      - "&7purple accents and modern styling"
      - ""
      - "&7Features:"
      - "&8• Dark color palette"
      - "&8• Purple highlighting"
      - "&8• Compact layouts"
      - "&8• Ambient effects"
      - ""
      - "{if:{equals:{player.current_theme}:dark}:&a✓ Currently Active:&e» Click to Activate}"
    enchant_if: "{equals:{player.current_theme}:dark}"
    actions:
      left_click:
        type: "switch_theme"
        params:
          theme: "dark"
          gui: "main-menu-dark"
  
  # Neon theme option
  neon_theme:
    type: "button"
    slot: 14
    material: "CYAN_STAINED_GLASS"
    name: "&b&lNeon Theme"
    lore:
      - "&7High-energy cyber interface"
      - "&7with electric colors and effects"
      - ""
      - "&7Features:"
      - "&8• Electric cyan colors"
      - "&8• Cyber terminology"
      - "&8• Lightning effects"
      - "&8• Advanced layouts"
      - "&8• Holographic elements"
      - ""
      - "{if:{equals:{player.current_theme}:neon}:&a✓ Currently Active:&e» Click to Activate}"
    enchant_if: "{equals:{player.current_theme}:neon}"
    actions:
      left_click:
        type: "switch_theme"
        params:
          theme: "neon"
          gui: "main-menu-neon"
  
  # Medieval theme option
  medieval_theme:
    type: "button"
    slot: 16
    material: "OAK_WOOD"
    name: "&6&lMedieval Theme"
    lore:
      - "&7Fantasy-themed interface with"
      - "&7earthy tones and medieval styling"
      - ""
      - "&7Features:"
      - "&8• Gold and earth tones"
      - "&8• Medieval terminology"
      - "&8• Wooden textures"
      - "&8• Royal effects"
      - "&8• Classic fantasy feel"
      - ""
      - "{if:{equals:{player.current_theme}:medieval}:&a✓ Currently Active:&e» Click to Activate}"
    enchant_if: "{equals:{player.current_theme}:medieval}"
    actions:
      left_click:
        type: "switch_theme"
        params:
          theme: "medieval"
          gui: "main-menu"  # Uses default main menu with medieval theme
  
  # Spacer elements
  spacer:
    type: "static"
    slots: [11, 13, 15]
    material: "GRAY_STAINED_GLASS_PANE"
    name: " "
    hide_flags: true
  
  # Border elements
  border:
    type: "border"
    slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
    material: "BLACK_STAINED_GLASS_PANE"
    name: " "
    hide_flags: true

# Navigation
navigation:
  back_button:
    enabled: true
    slot: 0
    target_gui: "{previous_gui}"
  
  close_button:
    enabled: true
    slot: 8

# Theme selector effects
effects:
  open_sound: "UI_BUTTON_CLICK"
  close_sound: "UI_BUTTON_CLICK"
  
  theme_switch_sound: "ENTITY_PLAYER_LEVELUP"
  
  particle_effects:
    enabled: false  # Keep neutral for theme selection

# Features
features:
  remember_previous: true
  instant_switching: true
  preview_mode: false  # Could be added later
  
  confirmation_required: false
  save_preference: true